name: flutter_my_core_library
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  #google
  cupertino_icons: ^1.0.2
  change_app_package_name:
  speech_to_text: ^6.1.1
  fluttertoast: ^8.1.2
  dropdown_search: ^5.0.6
  flutter_launcher_icons:
  intl:
  email_validator:
  intl_phone_number_input:
  font_awesome_flutter:
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  upgrader: ^6.0.1
  package_info_plus:


  #firebase
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.2
  google_sign_in: ^6.0.1


  #State management
  flutter_bloc:

  #Network
  connectivity_plus:
  vexana: ^3.4.1

  #cache
  hive_flutter:

  #animation
  avatar_glow:




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^1.1.3







  flutter_lints: ^2.0.0


flutter:
  assets:
    - asset/image/nopage.png
  uses-material-design: true

































