name: flutter_my_core_library
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  intl:
  shared_preferences:
  connectivity_plus:
  http:
  flutter_bloc:
  change_app_package_name:
  fluttertoast:
  flutter_datetime_picker:
  dropdown_search: ^3.0.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  dio: ^4.0.6
  vexana:
  hive_flutter: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^1.1.3







  flutter_lints: ^2.0.0


flutter:
  assets:
    - asset/image/nopage.png
  uses-material-design: true

































